# Generated by Django 4.0.1 on 2022-05-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
    ]
