# Generated by Django 3.2.4 on 2022-05-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerapi', '0002_alter_command_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='task_id',
            field=models.IntegerField(),
        ),
    ]
