# Generated by Django 4.0.1 on 2022-06-05 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controllerapi', '0004_auto_20220522_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='command',
            name='recurrence_exceptions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='command',
            name='recurrence_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='command',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='command',
            name='frequency',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='command',
            name='task_type',
            field=models.CharField(blank=True, choices=[('onetime', 'OneTime'), ('recurrent', 'Recurrent')], max_length=100),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(default=0)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_id', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.CharField(blank=True, choices=[('soil_moisture', 'Soil_Moisture'), ('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('device_id', models.ManyToManyField(to='controllerapi.Device')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='device_id',
            field=models.ManyToManyField(to='controllerapi.Device'),
        ),
    ]
