# Generated by Django 4.0.1 on 2022-06-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllerapi', '0006_sensor_task_rename_device_name_device_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='sensor',
        ),
    ]
