# Generated by Django 4.0.1 on 2022-06-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controllerapi', '0007_remove_data_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controllerapi.sensor'),
        ),
    ]
