# Generated by Django 4.0.1 on 2022-06-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllerapi', '0008_data_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='taskType',
        ),
    ]
