# Generated by Django 4.0.1 on 2022-06-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllerapi', '0009_rename_type_task_tasktype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskType',
            new_name='_type',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
